import AppKit
import Foundation

@MainActor
extension WebPanelController {
    func imagePlacementSnapshot() -> [String: Any] {
        let id = store.appSnapshot.selectedWallpaperId
        let displayID = navigation.targetDisplayID
        let displaySupported = store.settingsSnapshot.displays.contains {
            $0.displayId == displayID && $0.enabled && $0.mode == .standalone
        }
        let installed = id.map { id in store.librarySnapshot.wallpapers.contains { $0.id == id } } ?? false
        let info = installed ? id.flatMap { imagePlacement.generatedImage(wallpaperID: $0) } : nil
        let custom = id.flatMap { imagePlacement.placement(wallpaperID: $0, displayID: displayID) }
        var fit = info?.fit
        if let id, let options = store.wallpaperOptionsSnapshot, options.wallpaperId == id,
           let property = options.properties.first(where: { $0.id == "fit" }),
           case .string(let value) = property.value, let appliedFit = StillImageWallpaper.Fit(rawValue: value) {
            fit = appliedFit
        }
        var snapshot: [String: Any] = [
            "wallpaperID": id as Any? ?? NSNull(), "displayID": displayID,
            "supported": info != nil && displaySupported,
            "x": custom?.x ?? 0.5, "y": custom?.y ?? (fit == .fillTop ? 0 : 0.5),
            "zoom": custom?.zoom ?? 1, "customized": custom != nil,
        ]
        if let fit { snapshot["fit"] = fit.rawValue }
        if let size = info?.imagePixelSize {
            snapshot["imagePixelSize"] = ["width": size.width, "height": size.height]
        }
        if let info { snapshot["imageAspectRatio"] = info.imageAspectRatio }
        let displayTitle = store.settingsSnapshot.displays.first { $0.displayId == displayID }?.title ?? ""
        let physicalID = ResolvedDisplayTitles.liveDisplayID(displayID, title: displayTitle)
        if let screen = NSScreen.screens.first(where: {
            ($0.deviceDescription[NSDeviceDescriptionKey("NSScreenNumber")] as? NSNumber)?.uint32Value == physicalID
        }), screen.frame.height > 0 {
            snapshot["displayAspectRatio"] = screen.frame.width / screen.frame.height
            snapshot["displayViewportSize"] = ["width": screen.frame.width, "height": screen.frame.height]
            snapshot["displayPixelSize"] = ["width": screen.frame.width * screen.backingScaleFactor,
                                             "height": screen.frame.height * screen.backingScaleFactor]
        }
        if !displaySupported {
            snapshot["reason"] = String(localized: "Image placement requires an enabled independent display.")
        } else if info == nil {
            snapshot["reason"] = String(localized: "Image placement is available only for unmodified image pages generated by WallpaperMachine.")
        }
        return snapshot
    }

    func performImagePlacement(_ action: String, request: WebPanelRequest) async throws -> Bool {
        guard action == "imagePlacement" || action == "imagePlacementReset" else { return false }
        let id = try wallpaperID(request)
        let displayID = try request.string("displayID")
        try validatePlacementDisplay(displayID)
        let placement: StillImagePlacement?
        if action == "imagePlacement" {
            placement = try StillImagePlacement(x: request.number("x", range: 0...1),
                y: request.number("y", range: 0...1), zoom: request.number("zoom", range: StillImagePlacement.zoomRange))
        } else { placement = nil }
        let key = id + "\u{0}" + displayID
        imagePlacementRequestSequence &+= 1
        let requestSequence = imagePlacementRequestSequence
        imagePlacementRequests[key] = requestSequence
        defer {
            if imagePlacementRequests[key] == requestSequence { imagePlacementRequests[key] = nil }
        }
        guard try await imagePlacement.prepare(wallpaperID: id) != nil else {
            throw WallpaperActionError(message: String(localized: "This wallpaper is not an unmodified image page generated by WallpaperMachine."))
        }
        guard imagePlacementRequests[key] == requestSequence else { return true }
        try Task.checkCancellation()
        // Preparation suspends: reject a target that was removed or disabled in the meantime.
        _ = try wallpaperID(request)
        try validatePlacementDisplay(displayID)
        if let placement {
            try imagePlacement.set(placement, wallpaperID: id, displayID: displayID)
        } else {
            try imagePlacement.reset(wallpaperID: id, displayID: displayID)
        }
        return true
    }

    private func validatePlacementDisplay(_ displayID: String) throws {
        guard store.settingsSnapshot.displays.contains(where: {
            $0.displayId == displayID && $0.enabled && $0.mode == .standalone
        }) else { throw WebPanelRequest.invalid }
    }
}
